[project]
name = "travel-advisor-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "google-adk[db,eval]>=1.12.0",
    "google-genai>=1.31.0",
    "greenlet>=3.5.4",
    "litellm>=1.76.0",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.51",
    "sseclient-py>=1.8.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
